### ISSUE TITLE
gevent error in main.py

### ISSUE THREAD

**Issue by eqpaisley** [fHDHR/fHDHR#108]
Brand new Ubuntu 20 server. Installing per the instructions. When I run main.py I get this error:
```

File "main.py", line 4, in <module>
    from gevent import monkey

```

**Comment by deathbybandaid** [comment]
did you do `pip3 install -r requirements.txt`

https://github.com/fHDHR/fHDHR/blob/main/requirements.txt#L2

**Comment by eqpaisley** [comment]
I did, both for the main install and again after installing the plutotv plugin. 

https://pastebin.com/TqcdjdWK

**Comment by deathbybandaid** [comment]
What version of python are you running this with?
`python3 --version`

**Comment by eqpaisley** [comment]
3.8.5

![image](https://user-images.githubusercontent.com/5481431/107810931-6d595080-6d3b-11eb-9cfe-6e8322f7adeb.png)

**Comment by deathbybandaid** [comment]
And you are running `python3 main.py`

**Comment by eqpaisley** [comment]
Yup.

![image](https://user-images.githubusercontent.com/5481431/107811126-b14c5580-6d3b-11eb-9946-9b45ac969ed9.png)

**Comment by deathbybandaid** [comment]
try `sudo pip3 install -r requirements.txt`

**Comment by eqpaisley** [comment]
That worked.   Any idea why that worked? I had already done pip3 requirements twice.  Maybe not being `sudo `when I did it prevented something critical from installing?

**Comment by deathbybandaid** [comment]
installing requirements with `pip3` installs for your user. `sudo pip3` installs it as root

**Comment by eqpaisley** [comment]
Ok, thanks.
