### ISSUE TITLE
Change in Behavior: Plex Devices

### ISSUE THREAD

**Issue by tharris9d** [fHDHR/fHDHR#129]
@deathbybandaid Before changing to the Plug-in format I would be able to add both of my Locast accounts and it would show up in Plex as 2 separate devices. I only had to change the friendlyname and reporting_firmware_name and make sure the uuid was unique to each.
Since the change when I go to add the second device on port 5006 it just overwrites the original device on Port 5005. My goal is to have 2 accounts (devices) with 3 tuners each. Any help would be appreciated.
Thanks, 
Tom

**Comment by deathbybandaid** [comment]
You'll want to use xteve

**Comment by tharris9d** [comment]
xteve is worthless. I've tried a bunch of combinations but the streams drop constantly. Plex allows multiple HD Home Run devices or a combination of devices. It worked fine up until the new Plug-in Version so I am thinking something isn't getting passed through to Plex the same.

**Comment by deathbybandaid** [comment]
Are you using the full hdhr paths from the hdhr tab of the webui?

**Comment by tharris9d** [comment]
I will double-check
