### ISSUE TITLE
xmltv_offset issue with the Stirr plugin

### ISSUE THREAD

**Issue by badtou** [fHDHR/fHDHR#135]
The configuration setting for xmltv offset is not applied in the stirr plugin when using the latest build.
Testing this using Ubuntu and Channels DVR

**Comment by deathbybandaid** [comment]
I'll get a fix for this tomorrow.

**Comment by deathbybandaid** [comment]
Should work as of 

https://github.com/fHDHR/fHDHR/pull/137

I'll be pushing some code to the origin/epg plugins to allow changing this without restarting the web interface

**Comment by badtou** [comment]
Thanks for the quick response!
