### ISSUE TITLE
Cant see fHDHR in Plex

### ISSUE THREAD

**Issue by Chris230291** [fHDHR/fHDHR#136]
I am unable to connect to fHDHR in Plex using the default fHDHR settings.
I have tried specifying the same (working) web UI credentials but Plex wont connect.
I have tried playing with different combinations of settings, but at this point I don't know what I have and haven't tried.

Any ideas?

**Comment by deathbybandaid** [comment]
What plugins do you have installed

**Comment by Chris230291** [comment]
TVH and PlutoTV

**Comment by deathbybandaid** [comment]
You need the hdhr interface plugin

**Comment by Chris230291** [comment]
Right... its even in the docs. I overlooked it. 
I assume it doesn't work (in Plex) because I am not transcoding it?
Or should it work without ffmpeg/vlc?

**Comment by deathbybandaid** [comment]
It does work in plex with the hdhr plugin

**Comment by deathbybandaid** [comment]
From the HDHR web interface tab, copy the links into Plex

![image](https://user-images.githubusercontent.com/18010545/109310871-152e4e00-7813-11eb-8df6-a904bffdc4fb.png)

![image](https://user-images.githubusercontent.com/18010545/109311057-4d359100-7813-11eb-8af4-459697a57fd8.png)

**Comment by Chris230291** [comment]
Yes I was using it correctly.
Today is a new day and for some reason it has started working.
Yesterday I could add the device but nothing would play. When I checked on the "tuner" it would say it was no longer available.

Now that it is working it seems very slow with TVH. Not sure if that's my end or just how it works? From clicking play on a channel in Plex to seeing it appear under "subscriptions" in the TVH web UI is about 20 seconds.

**Comment by Chris230291** [comment]
It has stopped working again now "Playback Error Could not tune channel"
If I go into the fHDHR web UI and download the m3u, channels play in VLC instantly.

**Comment by deathbybandaid** [comment]
Then that seems to be an issue with your plex connecting to fhdhr

**Comment by Chris230291** [comment]
Is it normal to have all of these recordings in Plex? I am not trying to recording anything.

![Screenshot_1](https://user-images.githubusercontent.com/5328818/109348679-c6ad9d80-786c-11eb-91c6-276cd4018352.png)

**Comment by deathbybandaid** [comment]
it's normal if you click the record button...

**Comment by Chris230291** [comment]
After a bit of research it seems "recording" isn't actually recording in this case, it means "streaming".
