### ISSUE TITLE
epg update_frequency does not actually update the epg

### ISSUE THREAD

**Issue by badtou** [fHDHR/fHDHR#143]
Although the logging indicates that the epg cache is updated on schedule, the only way to actually update epg is to restart or click the link in the web interface to update the the cache.

**Comment by deathbybandaid** [comment]
I'm running all but one origin plugin, and not experienced epg not updating

**Comment by badtou** [comment]
I'm seeing this with plutotv epg since the guide is so short that it runs out after about 6 hours.  The guide in the web interface shows that the content description is unavailable until it it manually refreshed using the web interface.

**Comment by badtou** [comment]
It could be working for me after I installed system updates to Ubuntu, but now I've seen a different error pop up.  I will reboot and let it run overnight before reporting back tomorrow with an update.

**Comment by badtou** [comment]
Update information - The attached file shows normal operation up until 11 PM. However sometime before midnight the console displayed the error I included in the attached file which I believe is preventing the scheduler from from updating the epg.  
[.fHDHR (copy).log](https://github.com/fHDHR/fHDHR/files/6076778/default.fHDHR.copy.log)

**Comment by deathbybandaid** [comment]
That error is unrelated to EPG, but I've just pushed a fix for it.

**Comment by badtou** [comment]
The error might have been unrelated to updating the epg, but fixing it corrected the issue with the scheduler not running the epg update.
