### ISSUE TITLE
USTVGO plugin error

### ISSUE THREAD

**Issue by Protektor-Desura** [fHDHR/fHDHR#158]
I am getting this error on the USTVGO plugin

Traceback (most recent call last):
  File "/app/main.py", line 16, in <module>
    sys.exit(run.main(SCRIPT_DIR, fHDHR_web))
  File "/app/fHDHR/cli/run.py", line 108, in main
    returned_code = start(args, script_dir, fHDHR_web)
  File "/app/fHDHR/cli/run.py", line 92, in start
    plugins.load_plugins(logger, db)
  File "/app/fHDHR/plugins/__init__.py", line 249, in load_plugins
    plugin_item = Plugin(self.config, self.logger, self.db, plugin_name, plugin_path, plugin_conf, plugin_manifest)
  File "/app/fHDHR/plugins/__init__.py", line 110, in __init__
    self._module = self._load()
  File "/app/fHDHR/plugins/__init__.py", line 129, in _load
    mod = imp.load_module(self.plugin_dict_name, None, self.path, description)
  File "/usr/lib/python3.8/imp.py", line 244, in load_module
    return load_package(name, filename)
  File "/usr/lib/python3.8/imp.py", line 216, in load_package
    return _load(spec)
  File "<frozen importlib._bootstrap>", line 702, in _load
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/app/plugins/fHDHR_plugin_origin_USTVGO/origin/__init__.py", line 6, in <module>
    from seleniumwire import webdriver
ModuleNotFoundError: No module named 'seleniumwire'

**Comment by deathbybandaid** [comment]
You need to install the seleniumwire module for python

**Comment by Protektor-Desura** [comment]
I should mention it isn't listed in your required.txt file for your docker. I did add it to my docker though. seleniumwire though is not valid. It is selenium-wire.

"ERROR: Could not find a version that satisfies the requirement seleniumwire (from versions: none)
ERROR: No matching distribution found for seleniumwire"



```
FROM ghcr.io/linuxserver/baseimage-ubuntu:focal

ARG FHDHR_RELEASE
ARG DEBIAN_FRONTEND="noninteractive"
LABEL maintainer="protektor"

# environment settings
ENV HOME="/app"

RUN apt-get -qq update && \
    apt-get -qq -y install gpg && \
    apt-key adv --keyserver keyserver.ubuntu.com --recv-keys F63F0F2B90935439 && \
    echo "deb http://ppa.launchpad.net/kisak/kisak-mesa/ubuntu focal main" > /etc/apt/sources.list.d/kisak-ubuntu-kisak-mesa-focal.list && \
    apt-get update && \
    apt-get upgrade -y && \
    apt-get autoclean

RUN apt-get -qq update && \
    apt-get -qq -y install gcc ffmpeg vlc python3-pip && \
    apt-get autoclean

RUN pip3 install requests gevent flask image m3u8 sqlalchemy pycryptodome simplejson selenium-wire selenium

RUN apt-get -qq update && \
    apt-get -qq -y remove gcc && \
    apt-get autoclean && \
    rm -rf /var/lib/apt/lists/*


COPY ./ /app/
WORKDIR /app

EXPOSE 1900 5004
VOLUME /config
ENTRYPOINT ["python3", "/app/main.py", "--config", "/config/config.ini"]


```

**Comment by Protektor-Desura** [comment]
Now I am getting this error.

ImportError: pafy: youtube-dl not found; you can use the internal backend by setting the environmental variable PAFY_BACKEND to "internal". It is not enabled by default because it is not as well maintained as the youtube-dl backend.

**Comment by deathbybandaid** [comment]
`apt install youtube-dl`

Docs for plugins need to be developed. Easy PRs for somebody with time.
