### ISSUE TITLE
Unable to uncheck "Enabled" in channel editor

### ISSUE THREAD

**Issue by tlspambait** [fHDHR/fHDHR#164]
Hi,

When ever I uncheck the "Enabled" box and then either hit modify on that channel or modify all, on reloading the setting is lost and the change reverts back and the channel is is re-enabled.

Also if I select a channel as a favourite and save it, it saves.  If you attempt to then uncheck the favourite channel, like the enabled issue above, the box always comes back as checked after modifying.

**Comment by deathbybandaid** [comment]
Disable a channel, and then check the `enabled` for that channel at `ip:port/api/channels?method=get`

**Comment by tlspambait** [comment]
It's changing the enabled to false, but as all the checkbox reappears as checked on /channels_editor, if you make any further changes and hit modify or modify all, it will revert them back to true.

So they only way to make it stick would appear to be waiting until you've made all your modifications (channel numbers etc), unselecting the channels you want, and they you get one shot at disabling them, otherwise if you try to do further edits you're stuck with them all checked as enabled.  (I've tried both chrome and safari trying to ensure it's not a web browser issue).

**Comment by tlspambait** [comment]
I think i've diagnosed how to fix the issue, it seems to be in the HTML code that keeps rendering the page with the checkbox checked (i've tried a range of browsers and OS).

The following line in the code
<input type="checkbox" class="channels" name="enabled" value="True" **checked=""** placeholder="True">

the bold text above, will always display the checkboxed checked, which is what keeps getting rendered on reloading the page.

It needs to be rewritten to omit the `checked=""` in the tag so that it doesn't show up as checked.  As I understand it, as soon as the "checked" is in the tag it becomes checked the value of the checked tag is ignored so there is no need for it to be ="" as it could be ="pineapple" and the box would still end up being checked.

For example:
`<input type="checkbox" class="channels" name="enabled" value="True" placeholder="False">`

**Comment by deathbybandaid** [comment]
#170 should fix this behavior

**Comment by deathbybandaid** [comment]
As well as #171 fixing the root of a related issue, where values were being stored as string instead of bool
