### ISSUE TITLE
Movie: is prefixed to all xmltv episode titles

### ISSUE THREAD

**Issue by johnmmcgee** [fHDHR/fHDHR#176]
It seems that no matter what type of program is being utilized, there is a "Movie:" prefix affixed to any show title on the EPG output when pulling data from either tvtv or zap2it.

Example XML:
`
<programme start="20210904150000 +0000" stop="20210904153000 +0000" channel="27">

<title lang="en">Pet Vet Dream Team</title>

<desc lang="en">

Talented veterinarians deal with compelling cases of infirm and injured pets. We will also see animal expert Tim Faulkner in action at the Australian Reptile Park, where he cares for animals big and small, from crocodiles to koalas.

</desc>

**<sub-title lang="en">Movie: </sub-title>**

<length units="minutes">30</length>

<icon src="https://cdn.tvpassport.com/image/station/100x100/cbs.png"/>

<rating system="MPAA">

<value>TVY7</value>

</rating>

</programme>`

Offending line of code in xmltv.py:
`sub_el(prog_out, 'sub-title', lang='en', text='Movie: %s' % program['sub-title'])`

**Comment by deathbybandaid** [comment]
Try https://github.com/fHDHR/fHDHR/pull/185

**Comment by johnmmcgee** [comment]
It seems to improve it, however there are still a lot of items marked/treated as movies.  Example, news.

Is the movie prefix necessary?  Is there a way to remove it unless the show is marked as a movie?

Perhaps make it an option if its something you enjoy?

Also, apologies.  It looks like my xml copy and paste output didn't show up accurately.

**Comment by deathbybandaid** [comment]
The origin needs to report season/episode numbers to not be a "movie"

**Comment by johnmmcgee** [comment]
I completely understand that.  However, not everything that does not supply those items is a movie.  

It would be a feature request to make it an optional item all together.
