### ISSUE TITLE
Possible use

### ISSUE THREAD

**Issue by jcastilloalonso** [fHDHR/fHDHR#202]
Hi,

I learned that my ISP offers an IPTV source (m3u source), yet asks to be used inside my home internet. My Plex server is hosted in a faster connection, yet that server has a wireguard vpn over to my home in a 2nd IP address.

So I'm wondering if fHDHR (and maybe other tools) could be used to serve the m3u over to Plex as live tv. I would basically need the content to be binded to the vpn IP address instead of the primarily one as content to be able to be streamed.

Any ideas on this being currently possible? Still miss Locast too much, but need to find a workaround to watch TV on the go.

Thanks a lot for your help.

**Comment by deathbybandaid** [comment]
I'd suggest you start with looking at the origin plugins and coding one yourself

Basic needs is a channel listing, and a way to retrieve the m3u per channel.

If epg data is available, you can poke at their api for that.
