### ISSUE TITLE
Anyone successful in installing on an Nvidia Shield 2019

### ISSUE THREAD

**Issue by yarafie** [fHDHR/fHDHR#203]
Ran across this project and interested in using it.
I have an Nvidia Shield 2019 last model running a Plex Server.
Wondering if anyone has successfully installed this in Termux on the Nvidia Shield

Thanks

**Comment by yarafie** [comment]
After several trial and errors and searching on Google I managed to install it.
Got it up and running with the hdhr interface and ustvgo  originr using both Plex live tv and emby Live TV. epg for ustvgo doesn't seem to be correct though.
 
Now to figure out how to add my own m3u and epg links. Is their an interface and origin for that?

**Comment by deathbybandaid** [comment]
Congrats on your success.

No origin for thst currently, but you should be able to look at how the origin plugins work, and write one pretty easily!

**Comment by yarafie** [comment]
> Congrats on your success.
> 
> No origin for thst currently, but you should be able to look at how the origin plugins work, and write one pretty easily!

Thanks. 

Which of the Origins do you suggest I should use as a base to try and code a general m3u & epg Origin?
I assume I need not worry about interface and just rely on hdhr one.

**Comment by deathbybandaid** [comment]
https://github.com/fHDHR/fHDHR_plugin_origin_Youtube/blob/main/origin/__init__.py


All the origins have a similar structure. If you are hardcoding stuff, all you have to do is return some channel info and a channels m3u url.

Anything that uses m3u can be made into an origin super easy

**Comment by yarafie** [comment]
Thanks. Just spent few hours studying the origin codes to get an idea what's needed. 

get_channels is for creating the channel lists with the diff parameters return channel_list

get_channel_stream is for streams return stream_info but I can't figure out how to associate  the two

**Comment by deathbybandaid** [comment]
I usually use a channel id
