### ISSUE TITLE
Plex Connection Failing, but also discover.json

### ISSUE THREAD

**Issue by arrmo** [fHDHR/fHDHR#210]
Hi,

First off - my apologies if this is me! Trying to get Plex connectivity up to my (recently purchased) Ceton card ... some things going well, others ... well, pulling my hair out, and I can't afford that 🤣.

I was working with [fHDHR_Ceton](https://github.com/deathbybandaid/fHDHR_Ceton), and had that up and running somewhat (thanks!). I realized I should likely use fHDHR "directly" ... so set up, and running, in pyCharm (for debug - will send any PR's that make sense!), and the Ceton plugin. The web UI itself is working fine, but Plex isn't happy ... so I tried to take a look at discover.json myself (and also others, but this one is sufficient 😄). I try though a web browser (with the port as set up, and discover.json) ... nope. The same using curl. Thinking this is why Plex isn't happy, but not sure why this is the case.

No errors noted in the debugger or console, so that's not really a clue.

Any key pointers to my stupidity? Or is there a bit of an issue currently?

Thanks!

**Comment by deathbybandaid** [comment]
Do you have the hdhr interface plugin?

**Comment by deathbybandaid** [comment]
https://github.com/fHDHR/fHDHR_plugin_interface_hdhr

**Comment by arrmo** [comment]
That was it - thanks!!! As I said, my stupid 😞. I was reading through the Docs, but I must have missed that. 

Really appreciate the quick response!

**Comment by deathbybandaid** [comment]
PR's always welcome to improve the docs!

**Comment by arrmo** [comment]
Good point! Will do that - I owe you 😆

**Comment by arrmo** [comment]
OK, found where I missed it. It is there, but not 100% clear - at least for a dummy like me, LOL!

[PR ](https://github.com/fHDHR/fHDHR_Docs/pull/19)submitted - by all means comment / disagree.

Thanks again.
