### ISSUE TITLE
Add CTRL-C Handling

### ISSUE THREAD

**Issue by arrmo** [fHDHR/fHDHR#234]
From the console, it seems that CTRL-C won't stop fHDHR. I THINK it may be Flask related ... but in any case, capture and handle this key combination.

**Comment by arrmo** [comment]
OK, won't open any more quite yet 😆 . I can't seem to add a Label (enhancement)?

Thanks!

**Comment by deathbybandaid** [comment]
I'm aware, but i already have keyboar interrupt handling

https://github.com/fHDHR/fHDHR/blob/main/fHDHR/cli/run.py#L79

**Comment by arrmo** [comment]
Hmmm ... yep, see it there. Wondering if it's because Flask "takes over". Will take a look - if you want to close for now, I understand.
