### ISSUE TITLE
Additional Live TV Sources

### ISSUE THREAD

**Issue by Protektor-Desura** [fHDHR/fHDHR#235]
It would be nice to have the following streaming sites as plugins:

Distro TV
https://www.distro.tv/
Python script for Kodi to get Distro TV
http://www.ezzer-mac.com/_repo/plugin.video.distrotv/plugin.video.distrotv-1.0.1.zip

Plex TV
Python script for Kodi to get Plex Live streaming TV
https://k.slyguy.xyz/.repo/slyguy.plex.live/

Samsung TV Plus
https://www.samsung.com/us/televisions-home-theater/tvs/tvplus/
Python script for Kodi to get Samsung TV Plus
https://k.slyguy.xyz/.repo/slyguy.samsung.tv.plus/

PBS
https://k.slyguy.xyz/.repo/slyguy.pbs.live/

**Comment by deathbybandaid** [comment]
Looks like some good ideas. I can't promise getting to them very soon.

If you want, you can copy an existing plugin and modify it. I can give you pointers if you need help.

**Comment by deathbybandaid** [comment]
Wasted this morning trying to start on distrotv....

It pulls json from php at https://tv.jsrdn.com/tv_v5/getfeed.php

Problem is, even with the headers set the same as what that kodi script does, I get served a 404

**Comment by deathbybandaid** [comment]
As for the plextv one, the kodi plugin for this pulls the data from a non-Plex source

https://github.com/fHDHR/fHDHR/issues/147 might be a better example for this, but I can't see a clear way to easily get the channel list

**Comment by Protektor-Desura** [comment]
>Wasted this morning trying to start on distrotv....
>
>It pulls json from php at https://tv.jsrdn.com/tv_v5/getfeed.php
>
>Problem is, even with the headers set the same as what that kodi script does, I get served a 404

I just tried that link in a browser in Chrome and it gave me a bunch of channels information.



{
    "version": "5.0",
    "env": {
    "st": "20220131.201413",
    "gc": "US",
    "gr": "IL",
    "gd": "609",
    "gn": "",
    "ip": "66.190.135.171",
    "lt": "38.53170",
    "lg": "-89.99880",
    "bg": 7,
    "dev": 0
},
    "adtags": {
    "answer": {
        "cp": "tp",
        "url": "https:\/\/answermedia.trustedmarketplace.io\/ads\/processVast\/1330879?zip=__GEO_TYPE__&ifa=__DEVICE_ID__&ip=__CLIENT_IP__&appbundle=__APP_BUNDLE__&lon=__LONGITUDE__&dnt=__LIMIT_AD_TRACKING__&ua=__USER_AGENT__&usPrivacy=__IS_CCPA__&userid=__ADVERTISING_ID__&devicetype=__DEVICE__&gdpr=__IS_GDPR__&network=__DEVICE_CONNECTION_TYPE__&appname=__APP_NAME__&domain=__APP_DOMAIN__&width=__WIDTH__&dma=__GEO_DMA__&appstoreurl=__STORE_URL__&lat=__LATITUDE__&height=__HEIGHT__",
        "wt": 0,
        "sdk": "ott"
    },
    "elevator": {
        "cp": "en",
        "url": "https:\/\/securepubads.g.doubleclick.net\/gampad\/ads?sz=610x365&iu=\/6280\/video\/syndication\/distro-tv&env=vp&gdfp_req=1&impl=s&output=vast&unviewed_position_start=1&url=__PAGEURL__&correlator=__CACHE_BUSTER__&pmnd=0&pmxd=150000&pmad=6&pod=1&vpos=midroll&mridx=1&scor=__RANDOM_UUID__&vad_type=linear",
        "wt": 0,
        "sdk": "ott"
    },
    "ott_prod_gg_22574": {
        "cp": "gg",
        "url": "https:\/\/pubads.g.doubleclick.net\/gampad\/ads?iu=\/34230109\/ca-video-pub-3851171199385532-tag\/1124848439&description_url=http%3A%2F%2Fdistro.tv&env=vp&impl=s&correlator=&tfcd=0&npa=0&gdfp_req=1&output=vast&sz=640x480&unviewed_position_start=1&pmnd=0&pmxd=150000&pmad=5&vpa=0&vpmute=0&us_privacy=__CCPA_FLAG__&gdpr=__IS_GDPR__&gdpr_consent=__GDPR_CONSENT__",
        "wt": 314,
        "sdk": "ima_html5"
    },
    "ott_prod_gg_22677": {
        "cp": "gg",
        "url": "https:\/\/pubads.g.doubleclick.net\/gampad\/ads?iu=\/34230109\/ca-video-pub-3851171199385532-tag\/1093778564&description_url=http%3A%2F%2Fdistro.tv&env=vp&impl=s&correlator=&tfcd=0&npa=0&gdfp_req=1&output=vast&sz=640x480&unviewed_position_start=1&pmnd=0&pmxd=150000&pmad=5&vpa=0&vpmute=0&us_privacy=__CCPA_FLAG__&gdpr=__IS_GDPR__&gdpr_consent=__GDPR_CONSENT__",
        "wt": 314,
        "sdk": "ima_html5"
    },

**Comment by deathbybandaid** [comment]
Correct, works fine via browser, but I can't get anything via python
