### ISSUE TITLE
Capture Details of systemd Service

### ISSUE THREAD

**Issue by arrmo** [fHDHR/fHDHR#239]
I can try to help with this one as well. Log to file (seems to be stderr, not stdout, output?).

**Comment by arrmo** [comment]
OK, here is what I have right now - seems to be working ... though I would like to set the path once? `WorkingDirectory` or `RootDirectory` didn't seem to do it though?
```
[Unit]
Description=fHDHR Service
After=multi-user.target

[Service]
Type=simple
ExecStart=/mnt/ProgSSD/fHDHR/venv/bin/python3.9 /mnt/ProgSSD/fHDHR/main.py -c=/mnt/ProgSSD/fHDHR/config.ini
Restart=on-failure
RestartSec=5s
StandardOutput=file:/var/log/fHDHR.log
StandardError=file:/var/log/fHDHR.log

[Install]
WantedBy=multi-user.target
```

BTW, I also get a warning about running as root ... change it, or not really a worry?

Thanks!

**Comment by deathbybandaid** [comment]
I might add a systemd example in a `contrib` directory.

The root warning is exactly that, a warning.

**Comment by arrmo** [comment]
Sounds good to me, thanks! BTW, ExecStart does need full paths, so ignore that one 😆. More info here, https://askubuntu.com/questions/1063153/systemd-service-working-directory-not-change-the-directory

Service above is working => copy as you want, and close this issue?

Thanks!

**Comment by arrmo** [comment]
One minor update ... change `file:` above to `append:`

**Comment by deathbybandaid** [comment]
https://github.com/fHDHR/fHDHR/pull/245
