### ISSUE TITLE
Add UI Page Auto Refresh

### ISSUE THREAD

**Issue by arrmo** [fHDHR/fHDHR#240]
Just a thought, but add page refresh - automatically (perhaps using Ajax)?

Thanks!

**Comment by deathbybandaid** [comment]
fHDHR uses Brython to do fancy stuff in the web interface. It's more challenging to work with, but more pythonic

**Comment by arrmo** [comment]
Will take a look!

**Comment by arrmo** [comment]
OK, let me ask a question 😜. From what I can tell, Brython is Pythonic, like you say, but it's processing those Python commands / code through JS ... right? So - anything against doing the page refresh with JS? Asking because it's quite easy. For example, I just added this to base.html, and it refreshes the page every 5 seconds. Nice when looking at the tuners => auto update. But I don't want to spend too much time on it if you don't want JS used.

```
    <script type="text/javascript">
        function autoRefreshPage()
        {
            window.location = window.location.href;
        }
        setInterval('autoRefreshPage()', 5000);
    </script>
```
Thanks!

**Comment by deathbybandaid** [comment]
So the fun of Brython, is me writing the code without personally using javascript.

All the code I write is python.

**Comment by arrmo** [comment]
That makes sense. And I did some digging ... I did have it at least somewhat right. Seems Brython is a transpiler 😄.

Are you saying - no JS allowed / desired? Just trying to understand, sorry.

Thanks!

**Comment by deathbybandaid** [comment]
Correct

**Comment by arrmo** [comment]
OK, will try to figure out how to do it in Brython. BTW, seems I have to restart the server every time I make an html file change ... sound right? Asking as it makes debugging a lot slower - can't take the server down now for a few hours, folks using the tuner card ... LOL.

**Comment by arrmo** [comment]
Actually, it seems that perhaps Flask can be run standalone, from the command line - thinking that may be a way to debug => don't mess with the running version if fHDHR, and debug the UI separately. Have you tried that before? And if so ... any pointers on the command to run to debug? Just thinking I could run it on another port.

Or - can a second "copy" of fHDHR be run simultaneously ... different .ini file, different port? This may be more challenging though, as Flask is likely on a fixed port (80)?

Thanks!

**Comment by arrmo** [comment]
FYI, have a timer working in Brython ... triggering and all happy. What I can't find is how to reload / refresh a page (or element) from Brython. I admit, not seeing the documentation as great, but I may have just not found the right source yet.

**Comment by arrmo** [comment]
OK, I found a [good source](http://www.techtricky.com/how-to-refresh-page-or-part-of-the-page-automatically/) about refresh - it's JS, but it really does apply very closely (identically). I see a few options here, would like your thoughts,
1. Can use the meta tag. It does work ... but I don't really like it. It refreshes the full page. Ya, OK, the tuners update, but not sure we want the entire page refreshing every few seconds.
2. I added this code near the bottom of `base.html`, just to be able to test it out (and I added a button, named `auto-refresh`, also for testing),
```
<script type="text/python">
from browser import document
from browser import timer
from browser import window

def change_color():
    document['auto_refresh'].style.color = "blue"
    window.location = window.location.href
	
def press_button(ev):
    timer.set_timeout(change_color, 3000)

document['auto_refresh'].bind('click', press_button)		
</script>
```
Ya, it works, but again refreshes the full page - so not really liking it. `location.reload()` can also be used, but again - full refresh.

3. What I do like from that reference is the section `Refreshing part of a page periodically`, with frames. This would allow refreshing just the bottom half of the display, so tuners update automatically, etc. Thoughts? Asking because it would mean adding in frames - not sure what you think of that. It may also be possible without frames, but still some HTML adaptation.
4. BTW, jQuery looks pretty simple too, but I know you want to avoid JS. No issue, just making sure to give you the full story 😉 

Thanks!

**Comment by deathbybandaid** [comment]
It kinda has to load the whole page, the data displayed is formatted in flask for the whole page to render, and isn't able to pull bits of info from the Backend individually

**Comment by arrmo** [comment]
OK, then it's quite easy actually 😆. Just adding one (meta) line to base.html handles it ... and I checked, it really does work.

Make that value a variable (i.e. from the config file)?

Thanks!

**Comment by arrmo** [comment]
And really I guess - the page refresh doesn't bother me so much, but really want it on certain pages (only). Like the tuners, for example. Hmmm ... how to do that?!?!

**Comment by deathbybandaid** [comment]
Right now a global value for pages we want to refresh makes sense.

If page in refreshpagelist, add refresh tag

For plugins like webwatch, refreshing the page would be a bad time

**Comment by arrmo** [comment]
Agreed! And funny, I was thinking the same thing 👍. Meaning ... a list that auto-refresh.

Does this need to be a (new) function, defined and then accessed / called via Flask?

**Comment by deathbybandaid** [comment]
Not sure what you mean

**Comment by arrmo** [comment]
LOL - ya, I wasn't sure how to word that. Let me try to explain (better). What I was trying to say was that that line that needs to be added (to `<head>`) is (3 second refresh, for example)
```
<meta http-equiv="refresh" content="3">
```
But meaning to use Flask to return this string - if needed for the particular page. Sort of like,
```
{{ fhdhr.config.dict["fhdhr"]["friendlyname"] }}
```

=> use a variable / "calculation" to have Flask return the refresh (or not).

Clear as mud?

**Comment by deathbybandaid** [comment]
Okay, which pages do we want it on?

**Comment by arrmo** [comment]
My thought would be the following - agreed?
```
/ceton
/tuners
```
Any others you suggest?

Thanks!

**Comment by deathbybandaid** [comment]
I'm going to do some legwork for how this all works, I'll push something in the near future

**Comment by arrmo** [comment]
Thanks!

**Comment by deathbybandaid** [comment]
This took me much longer than I expected, had to make a few other changes to the codebase, and found some issues were caused by the scheduler thread taking over. Plugins can now specify a config setting in the internal json config called `pages_to_refresh` and is a comma seperated list.

The value must be the endpoint name

````
"pages_to_refresh":{
                      "value": "page_tuners_html",
                      "config_file": false,
                      "config_web": false,
                      "valid_options": ",",
                      "description": "A Comma Seperated list of pages to enable automatic refresh."
                  }
````


https://github.com/fHDHR/fHDHR/pull/242

**Comment by arrmo** [comment]
Will give this one a try, but to understand ... `/ceton` and `/tuners`, I'm thinking the first is in the origin plugin, the second in fHDHR. Do I have that right?

Thanks!

**Comment by deathbybandaid** [comment]
Tuners should refresh already, I didn't do ceton one though

**Comment by arrmo** [comment]
Added, and working 😄. Will push a PR to ceton. Thanks!

**Comment by arrmo** [comment]
PR pushed!
