### ISSUE TITLE
Log Output, Show Source File, Line Number

### ISSUE THREAD

**Issue by arrmo** [fHDHR/fHDHR#241]
Hi,

Just a thought, but for debugging (as IDE's like pyCharm seem to struggle with Flask / threading) ... have the log output routine also (prefix?) the line with the source file and line number, where the output is from? Makes zeroing in on the location very easy then.

Thanks!

**Comment by deathbybandaid** [comment]
I looked at doing this, but the log lines got too long to be useful

**Comment by deathbybandaid** [comment]
I think this may be feasible with some logging configuration,,, please stand by lol

**Comment by deathbybandaid** [comment]
https://github.com/fHDHR/fHDHR/pull/246

This allows the user to set a custom log format.

Additionally, it changes the default debug format to be more verbose than the other levels.

**Comment by arrmo** [comment]
Thanks! I see lots of updates today ... hold off updating my "production" setup yet? Production = if it breaks, I have a mad wife and kids 🤣

**Comment by deathbybandaid** [comment]
Spin up a second instance to play with?

**Comment by arrmo** [comment]
Was wondering about that the other day. Can I just run another instance => point to a different config.ini (e.g. configtest.ini)? Use a different fHDHR port, but share the Ceton card?

Thanks!

**Comment by deathbybandaid** [comment]
Possibly, or play with other origin plugins

**Comment by arrmo** [comment]
Enabled debug mode to check this, works great. Thanks!

**Comment by deathbybandaid** [comment]
you can also play around with the config setting and making a custom format

**Comment by arrmo** [comment]
I saw that, very cool! I do want to try it out 😄. To understand, in the config file, something like this (but modified) ... right?
```
[logging]
format = '[%(asctime)s] %(levelname)s - %(message)s'
```
Thanks!

**Comment by deathbybandaid** [comment]
Yes!

**Comment by arrmo** [comment]
Well you did make that easy ... LOL! I assume you have the path portion "hard" coded, right?

**Comment by deathbybandaid** [comment]
One of the first things in main.py is to save a variable for the current directory

**Comment by deathbybandaid** [comment]
Also add this to the forever growing list of undocumented features

**Comment by arrmo** [comment]
> One of the first things in main.py is to save a variable for the current directory

OK, let me dig a bit. Doesn't seem to be used in your format string - that's my confusion. Thanks!

**Comment by deathbybandaid** [comment]
`default_debug_log_format = '[%(asctime)s] p%(process)s {%(pathname)s:%(lineno)d} - %(levelname)s - %(message)s'`

**Comment by deathbybandaid** [comment]
When I did this, I kept the simpler logging for non-debug usecases

**Comment by arrmo** [comment]
Yep, see that now in the commit - I looked at the non-debug string. Thanks!!

Close this one then?
