### ISSUE TITLE
UnboundLocalError - failing on playback

### ISSUE THREAD

**Issue by arrmo** [fHDHR/fHDHR#254]
Hi,

I updated to the latest source, seeing this issue, now (when try to use a playlist),
```
UnboundLocalError: local variable 'stream_obj' referenced before assignment
2022-02-18T19:43:18Z {'REMOTE_ADDR': '192.168.2.91', 'REMOTE_PORT': '51148', 'HTTP_HOST': 'server:5006', (hidden keys: 20)} failed with UnboundLocalError
```

I "jumped back" to commit `99097417bd7eb62320dafd49c0cedcd1d132e137` ... then no issues. Or is it just me?

Thanks!

**Comment by deathbybandaid** [comment]
I'll take a look, and have a patch soon.

I moved stream code

**Comment by deathbybandaid** [comment]
You have a line number?

**Comment by deathbybandaid** [comment]
Without a file/line-number I can't track it down, but this PR might have fixed it.

https://github.com/fHDHR/fHDHR/pull/255

**Comment by arrmo** [comment]
Yep, seems to have - thanks!

I set the logs to debug, to get you the line number - and of course now it works ... LOL. Appreciate it!

**Comment by deathbybandaid** [comment]
I didn't encounter the issue in testing, as all my streams didn't error out

the new streaming system moved things out of the backend tuners as well as the tuners api, so it's a lot more fluid

**Comment by arrmo** [comment]
> the new streaming system moved things out of the backend tuners as well as the tuners api, so it's a lot more fluid

Sorry, just trying to understand 😆. Not sure quite what that means?

Thanks!
