### ISSUE TITLE
Able to change Locale?

### ISSUE THREAD

**Issue by Mattssn** [fHDHR/fHDHR#266]
Hello, I have successfully gotten the container up and working and pluto added and working in Jellyfin, the only thing I can't figure out is if there is some way to change the location Pluto thinks it is, I am in the US and my server is in Germany, all the channels are in German and I don't see any US news channels like I do on their web version. 

Thanks!

**Comment by deathbybandaid** [comment]
I honestly don't have any ideas for locale

**Comment by Mattssn** [comment]
Its more than likely just basing it off of IP, having the ability to use a proxy would be kinda beneficial

**Comment by deathbybandaid** [comment]
it's not a bad idea to write something into fHDHR to connect via proxy.

However, it will likely not be added until after the next release, as I'm in the middle of overhauling the streaming system.

**Comment by Mattssn** [comment]
That would be amazing, I can close this in the meantime, would you like to tag this as a suggestion. Nice work on fHDHR, its a pretty cool little app!

**Comment by deathbybandaid** [comment]
Looks like this might be fairly easy to implement

https://docs.python-requests.org/en/latest/user/advanced/#proxies


````
proxies = {
  'http': 'http://10.10.1.10:3128',
  'https': 'http://10.10.1.10:1080',
}
session = requests.Session()
session.proxies.update(proxies)

````

**Comment by deathbybandaid** [comment]
Just notes for future me regarding the config file:

````
[proxy]
enabled = 
proto = 
host = # IP or FQDN
port = 


[plugin_name]
proxy_enabled = 
proxy_proto = 
proxy_host = # IP or FQDN
proxy_port = 

````

The docs for implementing the proto in requests looks like we can specify a proxy per scheme/host match. Doing so would allow plugins to register that they need a specific scheme/host to proxy, and through a specific proxy. Since fHDHR support multiple origins, you could set a proxy for PlutoTV, but not for a local TVHeadend server.

**Comment by deathbybandaid** [comment]
as for the ffmpeg and VLC plugins, I'll have to investigate how to proxy those requests
