### ISSUE TITLE
config.ini, Parameters

### ISSUE THREAD

**Issue by arrmo** [fHDHR/fHDHR#275]
Hi,

I was struggling a bit with SSDP, partially because I was putting some parameters is incorrect sections - likely me, but I do see some slight disconnects. For example, from the [documentation](https://fhdhr.github.io/fHDHR_Docs/adv_config/#fhdhr),
```
[fhdhr]
# address = 0.0.0.0
# discovery_address = 0.0.0.0
# port = 5004
# tuner_count =  4
# friendlyname = fHDHR
# reporting_firmware_name = fHDHR
# reporting_manufacturer = BoronDust
# reporting_model = fHDHR
# reporting_firmware_ver = 20201001
# reporting_tuner_type = Antenna
# device_auth = fHDHR
# require_auth = False
# chanscan_on_start = True
```
But I found that this isn't quite right. I changed some parameters through the UI, let it save back to config.ini ... and got, for example,
```
[hdhr]
reporting_manufacturer = BoronDust
reporting_tuner_type = Cable
reporting_firmware_ver = 2013.0326.226
reporting_model = InfiniTV
reporting_firmware_name = InfiniTV
```

Is the correct mapping of variables to sections captured anywhere, and perhaps what the variables do? Or ... have a button to store all values (even with defaults) to config.ini, to allow editing / confirmation?

Thanks!

**Comment by deathbybandaid** [comment]
````
 ​    ​parser​.​add_argument​(​'--setup'​, ​dest​=​'setup'​, ​type​=​str​, ​required​=​False​, ​nargs​=​'?'​, ​const​=​True​, ​default​=​False​, ​help​=​'Setup Configuration file.'​)

````

Already a cli method

**Comment by deathbybandaid** [comment]
I don't do a good job keeping up on docs, most was written prior to the implementation of plugins.

**Comment by arrmo** [comment]
> I don't do a good job keeping up on docs, most was written prior to the implementation of plugins.

No worries! I'm the same 🤣.

Let me check out the cli, to help get the naming / assignment correct. Thanks!
