### ISSUE TITLE
Docker running as root.

### ISSUE THREAD

**Issue by Protektor-Desura** [fHDHR/fHDHR#324]
[2022-07-13 07:58:48,391] WARNING - Do not run fHDHR with root privileges.

```version: "2.1"
services:
  fhdhr-original:
    container_name: fhdhr
    hostname: fhdhr
    image: "fhdhr/fhdhr:latest"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    ports:
      - "5004:5004/tcp"
    volumes:
      - /home/docker/fhdhr:/app/config
      - /home/docker/fhdhr/plugins:/app/plugins
      - /home/docker/fhdhr/cache:/app/data/cache # Optional
    restart: unless-stopped
```

    
Thus the docker should be running as 1000:1000 but the logs say it is not. I think the problem is the base image your docker is build on doesn't support that.

**Comment by Protektor-Desura** [comment]
Also the docker does NOT download the plugins automatically or keep them up to date either. It should. That's the point of docker. Everything just works.

**Comment by Protektor-Desura** [comment]
You can check out what I did here:
https://github.com/Protektor-Desura/docker-fhdhr

**Comment by deathbybandaid** [comment]
@Berserkir-Wolf any thoughts on the docker stuff? I really hate docker and am unsure what any of the changes would actually do.

**Comment by Berserkir-Wolf** [comment]
Interesting find there, @Protektor-Desura - I'm not currently using the software (just don't have a use for it at present), but well spotted.
If you'd like to submit a PR for the dockerfile changes, I'd be happy to review them - I tried to shoehorn some of them in, but I've not got the time for a full review of it at the moment unfortunately.
