### ISSUE TITLE
PlutoTV plugin question

### ISSUE THREAD

**Issue by CTJohnK** [fHDHR/fHDHR#335]
@deathbybandaid I hope you are well.

I've been tinkering with this plugin.  Looking at the XMLTV data it generates, it appears PlutoTV only provides about an 8-hr window of programing for each EPG update.  So, I've eliminated all records which show 'Unavailable' in the Title for example.  I also adjusted the code which sets the time zone offset as it was always returning "None" which appears to cause Plex and Jellyfin some heartburn.

I'm now tinkering with the code which sets the season and episode values, but those do not appear to be returned within 'program'.  As you noted in the IPTV issue I opened earlier, these integrations change and you haven't had time to keep up with the changes.

I was hoping, since the PlutoTV web page does show season and episode if that data might be available now.  However, I cannot figure out where the code is that generates the request for EPG data from Pluto.  I presumed it was in xmltv.py, but that does not appear to be the case - or at least with my very limited knowledge of Python, I'm not seeing it.

I was wondering if you could point me to the code which pulls the EPG data from PlutoTV and I thought I would see if it now contained season and episode data.

**Comment by deathbybandaid** [comment]
Please close nd reopen on the plugins repository, thanks
