### ISSUE TITLE
TV Everywhere Support

### ISSUE THREAD

**Issue by Protektor-Desura** [fHDHR/fHDHR#52]
Channels-DVR is letting you use your cable subscription to login with Linux to stream and record your channels via TV Everywhere. It would cool to be able to do the same here.

https://en.wikipedia.org/wiki/TV_Everywhere

**Comment by eqpaisley** [comment]
+1 for this.  TV Everywhere integration is a game changer. Not sure how Channels is handling authentication (I think possibly using headless chrome instances to login and retrieve streams?)  But this is a very cool idea.

**Comment by deathbybandaid** [comment]
The trouble for me, is this isn't something I can develop. I don't pay for any service that implements this, so I have no way to test.

However, like the Ceton plugin, I am willing to work with somebody to provide an implementation, but somebody will have to write the initial code based on one of the existing origin plugins.
