### ISSUE TITLE
Find somebody willing to handle documentation for the project

### ISSUE THREAD

**Issue by deathbybandaid** [fHDHR/fHDHR#58]

**Comment by eqpaisley** [comment]
Happy to help write docs. Full disclosure, I'm an excellent writer but not a programmer. So you'd be getting readable docs from the perspective of a hobbyist, not an IT pro.

**Comment by deathbybandaid** [comment]
@eqpaisley Feel free to open PRs to the Docs Repo!

https://github.com/fHDHR/fHDHR_Docs

**Comment by Berserkir-Wolf** [comment]
@eqpaisley I've added a quick note on how to actually work with the framework [on the docs site itself](https://fhdhr.github.io/fHDHR_Docs/submitting_docs/)
