### ISSUE TITLE
Create config on launch

### ISSUE THREAD

**Issue by Berserkir-Wolf** [fHDHR/fHDHR#73]
Check config folder for config.ini on startup.
If not found, create with defaults.

**Comment by deathbybandaid** [comment]
I agree that we can make it work to create the config file if missing,,, however, the `-c=` still will need to specify where the config file will go.

**Comment by Berserkir-Wolf** [comment]
Have a default value for the config location, with an override available.
This will allow for mapping the config folder in a container, or for using your own folder that gets included in backups - but simplifies setup for inexperienced users.

**Comment by deathbybandaid** [comment]
https://github.com/fHDHR/fHDHR/pull/83

**Comment by Berserkir-Wolf** [comment]
Tested, works in docker container.
