### ISSUE TITLE
Include git in dockerfile

### ISSUE THREAD

**Issue by Berserkir-Wolf** [fHDHR/fHDHR#74]
Allow for using git clone repo to install plugins via webui

**Comment by Chris230291** [comment]
Hello. I was wondering if it would be possible to install, update, enable and disable plugins all from the web UI? I also use Docker but I think this would really benefit all users.

**Comment by deathbybandaid** [comment]
It's not possible at the moment, but it's something I'm actively looking into

**Comment by Chris230291** [comment]
Ok thanks for the reply. Is it the docker side that complicates things or something else?

**Comment by deathbybandaid** [comment]
Partly, yes. This IS beta software that I write in my downtime at work.

The plugin system is still VERY new. I only recently updated the versions page with a listing of official plugins.

There are other considerations, the script will have to be restarted to adapt to changes. Required config options could be an issue. Dependencies are a huge issue. As well as plugins that require ffmpeg/VLC to function.

**Comment by Chris230291** [comment]
What about if everything was included by default, all plugins and dependencies, then let users toggle them on/off? I think that solves almost all of the potential docker issues?

**Comment by Chris230291** [comment]
Ah OK well that makes sense.
It makes it more complicated with the requirements persisting between Docker restarts. I guess you could check the (I assume) mounted plugins dir on start up and install the requirements.

**Comment by Berserkir-Wolf** [comment]
@Chris230291 - the intention (at least to my mind) is to have a temp 'requirements' file that gets generated on load.
Have requirements files in each plugin folder, then at load find all files in subfolders and combine contents, deduplicate, and install.
