### ISSUE TITLE
Ceton Plugin discover.json 404 error

### ISSUE THREAD

**Issue by JSylvia007** [fHDHR/fHDHR#80]
Completely clean install, only added the ceton and streaming_ffmpeg plugins.

Channel search went just fine (took FOREVER), but appears to have completed without issue.  Found 900+ channels, this all checks out.  

Can't add my tuner to plex:

![image](https://user-images.githubusercontent.com/32574636/107106095-e6b2e980-67f7-11eb-8d77-f97bb1bdc678.png)

Related log entries (repeated multiple times):
```
2021-02-05 21:20:11,256 - fHDHR - DEBUG - Client is a Plex Media Server.
2021-02-05 21:20:11,257 - fHDHR - DEBUG - Client GET requested /discover.json Opening
2021-02-05 21:20:11,258 - fHDHR - DEBUG - Client GET requested /discover.json Closing
2021-02-05 21:20:11,267 - fHDHR - INFO - 10.1.60.99 - - [2021-02-05 21:20:11] "GET /discover.json HTTP/1.0" 404 1872 0.012496
```

Config:
```
[main]
uuid = xxjsxtxl

[fhdhr]
address = 10.1.60.99
port = 5004
tuner_count = 6
discovery_address = 10.1.60.99
friendlyname = fHDHR-Ceton
reporting_firmware_name = fHDHR_Ceton
reporting_manufacturer = BoronDust
reporting_model = fHDHR
reporting_firmware_ver = 20201001
reporting_tuner_type = Cable
device_auth = fHDHR
chanscan_on_start = true

[logging]
level = debug

[ceton]
ceton_ip = 10.1.60.180
stream_method = ffmpeg
tuner_count = 6
tuners = 6

[web_ui]
advanced = True
access_level = 2
```

**Comment by deathbybandaid** [comment]
Delete dvr, restart plex server, refresh plex webage in your browser and try again

**Comment by deathbybandaid** [comment]
Wait,,,, did you install the hdhr plugin?

**Comment by deathbybandaid** [comment]
https://github.com/fHDHR/fHDHR_plugin_interface_hdhr

**Comment by JSylvia007** [comment]
> Wait,,,, did you install the hdhr plugin?

I'm... I'm... Embarrassed... LOL
