### ISSUE TITLE
Import M3U & XML from URL/File

### ISSUE THREAD

**Issue by Protektor-Desura** [fHDHR/fHDHR#81]
Ability to put in a URL/File to import M3U and XMLTV from another provider so you can easily edit out channels you don't want. Also allows you to combine with other channels so you have one master channel list and one master guide.

**Comment by deathbybandaid** [comment]
That's actually already on the docket, with some logistical code being built into core. It's also something I'm looking atbdoing with the hdhr plugin to support multiple origins

**Comment by deathbybandaid** [comment]
as of today, the HDHR plugin now supports multiple origins, and I've added a "Delete Channel" button to the channel editor, both of which were foundations for working on this.

**Comment by Protektor-Desura** [comment]
Did we give up on this? Allowing us to import other M3U and XMLTV guides?

**Comment by deathbybandaid** [comment]
Didn't give up. Life got a little busy.

**Comment by go2tom42** [comment]
Is adding URL/File import of M3U and XMLTV files still on the table?
