### ISSUE TITLE
Serve Multiple Clients from a single Tuner

### ISSUE THREAD

**Issue by Protektor-Desura** [fHDHR/fHDHR#82]
It would be nice to be able to cache the streams using VLC or FFMPEG which are already included. It would also be nice to be able to put a limit for the number of streams per service and then display no more streams are available to clients if you pull more streams than allowed. This would also allow you to pull 1 stream and send it to multiple clients to save on bandwidth pulling from the internet.

**Comment by deathbybandaid** [comment]
Serving multiple clients with 1 stream is something I looked at a while back, but adds a great deal if overhead...

Ffmpeg is a plugin now, feel free to fork it and play with it in the meantime.

**Comment by deathbybandaid** [comment]
Also, regarding Stream limits, fHDHR currently only supports one origin plugin, but I have built in some logic to allow an origin plugin to specify the amount of tuners (defaults to 4), but is something I need to implement (maybe today).

**Comment by deathbybandaid** [comment]
https://github.com/fHDHR/fHDHR_plugin_origin_plutotv/commit/cbd60a33967b1842c5050e9a345af2666440a740

I did a similar commit for the other origin repos as well, this also unlocks each origin having its own streaming method.

**Comment by deathbybandaid** [comment]
The overhead for sharing connection streams isn't going to be ffmpeg/vlc related at all. This will need to be an added layer of the tuner interface, in a seperate thread with some sort of internal socket.

**Comment by deathbybandaid** [comment]
Just spent a couple hours poking at it, and at this time, serving multiple clients from a single tuner is not feasible.

**Comment by Protektor-Desura** [comment]
You might want to look at the code for xTeVe since they support doing this. It might give you some ideas.

**Comment by deathbybandaid** [comment]
Xteve is written in go, and fHDHR is python. It wouldn't help me much.

**Comment by Protektor-Desura** [comment]
I figured you could look at the logic they are using and how they are using VLC and FFMPEG to use the same logic (not code) to do the same thing but in python.

**Comment by Protektor-Desura** [comment]
ffmpeg has the ability to proxy built in. Here is an example command line.

/usr/bin/ffmpeg -user-agent "Mozilla/5.0 (QtEmbedded; U; Linux; C) AppleWebKit/533.3 (KHTML, like Gecko) MAG200 stbapp ver: 2 rev: 234 Safari/533.3" -i $url -map 0 -c copy -hide_banner -nostats -loglevel 0 -metadata service_provider=ffmpeg-proxy -metadata service_name=IPTV -f mpegts -

ffmpeg $FFMPEG_INPUT_ARGS -i $SOURCE_URL $FFMPEG_OUTPUT_ARGS -f rtsp rtsp://127.0.0.1:8554/$STREAM_NAME
